# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-21 04:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasabido', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Subtopico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasabido.Materia')),
            ],
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='dono',
        ),
        migrations.RemoveField(
            model_name='ajuda',
            name='tema',
        ),
        migrations.RemoveField(
            model_name='duvida',
            name='tema',
        ),
        migrations.AddField(
            model_name='ajuda',
            name='usuario',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='duvida',
            name='usuario',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
        migrations.AddField(
            model_name='ajuda',
            name='materia',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='tasabido.Materia'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ajuda',
            name='subtopico',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='tasabido.Subtopico'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='duvida',
            name='materia',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='tasabido.Materia'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='duvida',
            name='subtopico',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='tasabido.Subtopico'),
            preserve_default=False,
        ),
    ]
