# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-28 20:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasabido', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monitoria',
            name='data',
        ),
        migrations.RemoveField(
            model_name='monitoria',
            name='hora',
        ),
        migrations.AddField(
            model_name='duvida',
            name='data_monitoria',
            field=models.DateTimeField(blank=True, null=True, verbose_name=b'Data da monitoria'),
        ),
        migrations.AddField(
            model_name='duvida',
            name='segunda_data_monitoria',
            field=models.DateTimeField(blank=True, null=True, verbose_name=b'Data da monitoria 2'),
        ),
        migrations.AddField(
            model_name='duvida',
            name='terceira_data_monitoria',
            field=models.DateTimeField(blank=True, null=True, verbose_name=b'Data da monitoria 3'),
        ),
        migrations.AddField(
            model_name='monitoria',
            name='data_monitoria',
            field=models.DateTimeField(blank=True, null=True, verbose_name=b'Data da monitoria'),
        ),
        migrations.AddField(
            model_name='monitoria',
            name='segunda_data_monitoria',
            field=models.DateTimeField(blank=True, null=True, verbose_name=b'Data da monitoria 2'),
        ),
        migrations.AddField(
            model_name='monitoria',
            name='terceira_data_monitoria',
            field=models.DateTimeField(blank=True, null=True, verbose_name=b'Data da monitoria 3'),
        ),
        migrations.AlterField(
            model_name='duvida',
            name='data_criacao',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='duvida',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasabido.Materia'),
        ),
        migrations.AlterField(
            model_name='duvida',
            name='subtopico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasabido.Subtopico'),
        ),
        migrations.AlterField(
            model_name='duvida',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='monitoria',
            name='endereco',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='monitoria',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasabido.Materia'),
        ),
        migrations.RemoveField(
            model_name='monitoria',
            name='subtopico',
        ),
        migrations.AddField(
            model_name='monitoria',
            name='subtopico',
            field=models.ManyToManyField(to='tasabido.Subtopico'),
        ),
        migrations.AlterField(
            model_name='monitoria',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subtopico',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasabido.Materia'),
        ),
    ]
