# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-28 20:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasabido', '0006_auto_20160528_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='duvida',
            name='data_criacao',
            field=models.DateTimeField(auto_now=True, default=''),
            preserve_default=False,
        ),
    ]
