# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-24 20:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasabido', '0006_auto_20160524_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitoria',
            name='data_criacao',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
