# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-24 23:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasabido', '0008_auto_20160524_2059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monitoria',
            name='hora',
        ),
        migrations.AddField(
            model_name='monitoria',
            name='data_monitoria_dois',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='monitoria',
            name='data_monitoria_um',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
