# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-28 20:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasabido', '0008_auto_20160528_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duvida',
            name='data_criacao',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name=b'Data de criacao'),
        ),
    ]
