# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-28 20:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasabido', '0009_auto_20160528_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duvida',
            name='data_criacao',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
