# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-24 23:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasabido', '0009_auto_20160524_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitoria',
            name='data_monitoria',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
