# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-25 22:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasabido', '0010_auto_20160524_2341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monitoria',
            name='subtopico',
        ),
        migrations.AddField(
            model_name='monitoria',
            name='subtopico',
            field=models.ManyToManyField(to='tasabido.Subtopico'),
        ),
    ]
