# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-23 18:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasabido', '0011_qrcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moeda', models.IntegerField(default=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='moeda',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='qrcode',
            name='usuario',
        ),
        migrations.AlterField(
            model_name='duvida',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasabido.Aluno'),
        ),
        migrations.AlterField(
            model_name='monitoria',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasabido.Aluno'),
        ),
        migrations.DeleteModel(
            name='Moeda',
        ),
        migrations.DeleteModel(
            name='QrCode',
        ),
    ]
