# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-18 19:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasabido', '0012_auto_20160517_1922'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subtopico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_subtopico', models.CharField(max_length=100)),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasabido.Materia')),
            ],
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='curso',
            new_name='email',
        ),
    ]
