# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-01 01:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasabido', '0013_auto_20160630_0136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='duvida',
            name='data_monitoria',
        ),
        migrations.RemoveField(
            model_name='duvida',
            name='segunda_data_monitoria',
        ),
        migrations.RemoveField(
            model_name='duvida',
            name='terceira_data_monitoria',
        ),
        migrations.AddField(
            model_name='duvida',
            name='data_duvida',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='duvida',
            name='username',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
