# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-04 20:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasabido', '0014_auto_20160701_0114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='duvida',
            name='materia',
        ),
        migrations.AlterField(
            model_name='duvida',
            name='subtopico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duvidas', to='tasabido.Subtopico'),
        ),
        migrations.AlterField(
            model_name='materia',
            name='nome',
            field=models.CharField(max_length=100, unique=True, verbose_name=b'Materia'),
        ),
        migrations.AlterField(
            model_name='moeda',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moedas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='monitoria',
            name='subtopico',
            field=models.ManyToManyField(related_name='monitorias', to='tasabido.Subtopico'),
        ),
        migrations.AlterField(
            model_name='subtopico',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtopicos', to='tasabido.Materia'),
        ),
        migrations.AlterField(
            model_name='subtopico',
            name='nome',
            field=models.CharField(max_length=100, verbose_name=b'Subtopico'),
        ),
    ]
