# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-21 01:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasabido', '0014_auto_20160519_2041'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subtopico',
            old_name='nome_subtopico',
            new_name='nome',
        ),
    ]
