# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-08 11:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tasabido', '0015_auto_20160704_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='duvida',
            name='data_criacao_duvida',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 7, 8, 11, 58, 19, 394328, tzinfo=utc), verbose_name=b'Data criacao'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monitoria',
            name='data_criacao_monitoria',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 7, 8, 11, 58, 27, 954587, tzinfo=utc), verbose_name=b'Data criacao'),
            preserve_default=False,
        ),
    ]
