# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-09 00:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasabido', '0016_auto_20160708_1158'),
    ]

    operations = [
        migrations.RenameField(
            model_name='duvida',
            old_name='data_criacao_duvida',
            new_name='data_criacao',
        ),
        migrations.RenameField(
            model_name='monitoria',
            old_name='data_criacao_monitoria',
            new_name='data_criacao',
        ),
    ]
