# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-09 00:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasabido', '0017_auto_20160709_0034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duvida',
            name='data_criacao',
            field=models.DateTimeField(auto_now=True, verbose_name=b'Data criacao'),
        ),
        migrations.AlterField(
            model_name='monitoria',
            name='data_criacao',
            field=models.DateTimeField(auto_now=True, verbose_name=b'Data criacao'),
        ),
    ]
